version: '3.8'
services: 
  #mongodb
  mongodb:
    image: mongo:latest
    container_name: mongo_personal_website
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
      AUTH: admin
    ports:
      - '27023:27023'
    volumes:
      - 'mongodb_data:/data/db'
  #mongo-express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_personal_website
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_BASICAUTH_USERNAME: hello
      ME_CONFIG_BASICAUTH_PASSWORD: hellopassword
    ports:
      - '8083:8083'
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
